"""
app.py
A simple, user-friendly web interface for the Flash Separator Soft Sensor.

Lets you test any combination of feed Temperature, Pressure, and Mass Flow
and get an instant predicted Vapor Flow -- no need to edit ai_model.py or
rerun the simulation.

Run order: ai_model.py must have already been run at least once
(so that best_model.joblib exists in this folder), and that model must
be trained on Feed_Temperature_K, Feed_Pressure_atm, Feed_MassFlow_kg_s.

Usage:
    streamlit run app.py
"""

import os
import joblib
import pandas as pd
import streamlit as st

# ---- Load the trained model ----
current_dir = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(current_dir, "best_model.joblib")

st.set_page_config(page_title="Flash Separator Soft Sensor", page_icon="🌡️")

st.title("🌡️ Flash Separator Soft Sensor")
st.write(
    "This tool predicts **Vapor Flow (kg/s)** instantly from feed Temperature, "
    "Pressure, and Mass Flow, using a machine learning model trained on DWSIM "
    "simulation data — no need to rerun the full simulation."
)

if not os.path.exists(model_path):
    st.error(
        f"Could not find best_model.joblib in this folder.\n\n"
        f"Run `python ai_model.py` first to train and save the model."
    )
    st.stop()

model = joblib.load(model_path)

# ---- Training range warnings (based on the sweep ranges used in generate_dataset.py) ----
TEMP_MIN, TEMP_MAX = 290, 370
PRESSURE_MIN, PRESSURE_MAX = 1.0, 3.0
FLOW_MIN, FLOW_MAX = 1.0, 5.0

st.subheader("Enter Feed Conditions")

col1, col2, col3 = st.columns(3)

with col1:
    temperature = st.slider(
        "Feed Temperature (K)",
        min_value=250,
        max_value=420,
        value=325,
        step=1,
        help=f"Model trained on {TEMP_MIN}-{TEMP_MAX} K.",
    )

with col2:
    pressure = st.slider(
        "Feed Pressure (atm)",
        min_value=0.5,
        max_value=4.0,
        value=1.5,
        step=0.1,
        help=f"Model trained on {PRESSURE_MIN}-{PRESSURE_MAX} atm.",
    )

with col3:
    mass_flow = st.slider(
        "Feed Mass Flow (kg/s)",
        min_value=0.5,
        max_value=6.0,
        value=2.0,
        step=0.1,
        help=f"Model trained on {FLOW_MIN}-{FLOW_MAX} kg/s.",
    )

# Warn if any input is outside the training range (extrapolation)
warnings = []
if temperature < TEMP_MIN or temperature > TEMP_MAX:
    warnings.append(f"Temperature {temperature} K is outside the training range ({TEMP_MIN}-{TEMP_MAX} K).")
if pressure < PRESSURE_MIN or pressure > PRESSURE_MAX:
    warnings.append(f"Pressure {pressure} atm is outside the training range ({PRESSURE_MIN}-{PRESSURE_MAX} atm).")
if mass_flow < FLOW_MIN or mass_flow > FLOW_MAX:
    warnings.append(f"Mass Flow {mass_flow} kg/s is outside the training range ({FLOW_MIN}-{FLOW_MAX} kg/s).")

if warnings:
    st.warning(
        "WARNING: " + " ".join(warnings) +
        " The model is extrapolating here, so this prediction may be less reliable."
    )

# ---- Predict ----
test_data = pd.DataFrame({
    "Feed_Temperature_K": [temperature],
    "Feed_Pressure_atm": [pressure],
    "Feed_MassFlow_kg_s": [mass_flow],
})
predicted_vapor_flow = model.predict(test_data)[0]

st.metric(
    label="Predicted Vapor Flow",
    value=f"{predicted_vapor_flow:.4f} kg/s",
)

st.caption(
    "Prediction generated by the best-performing model "
    "(selected by R² during training in ai_model.py)."
)
