"""
app.py
A simple, user-friendly web interface for the Flash Separator Soft Sensor.

Instead of editing ai_model.py every time you want to test a new feed
temperature, this gives you a slider/input box in your browser.

Run order: ai_model.py must have already been run at least once
(so that best_model.joblib exists in this folder).

Usage:
    streamlit run app.py
"""

import os
import joblib
import pandas as pd
import streamlit as st

# ---- Load the trained model ----
current_dir = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(current_dir, "best_model.joblib")

st.set_page_config(page_title="Flash Separator Soft Sensor", page_icon="🌡️")

st.title("🌡️ Flash Separator Soft Sensor")
st.write(
    "This tool predicts **Heater Duty (kW)** instantly from a feed temperature, "
    "using a machine learning model trained on DWSIM simulation data — "
    "no need to rerun the full simulation."
)

if not os.path.exists(model_path):
    st.error(
        f"Could not find best_model.joblib in this folder.\n\n"
        f"Run `python ai_model.py` first to train and save the model."
    )
    st.stop()

model = joblib.load(model_path)

# ---- Training range warning ----
TRAIN_MIN = 290
TRAIN_MAX = 370

st.subheader("Enter a Feed Temperature")

temperature = st.slider(
    "Feed Temperature (K)",
    min_value=250,
    max_value=420,
    value=325,
    step=1,
    help=f"The model was trained on data from {TRAIN_MIN} K to {TRAIN_MAX} K.",
)

# Warn if outside the training range (extrapolation)
if temperature < TRAIN_MIN or temperature > TRAIN_MAX:
    st.warning(
        f"⚠️ {temperature} K is outside the training range "
        f"({TRAIN_MIN}–{TRAIN_MAX} K). The model is extrapolating here, "
        f"so this prediction may be less reliable."
    )

# ---- Predict ----
test_data = pd.DataFrame({"Feed_Temperature_K": [temperature]})
predicted_duty = model.predict(test_data)[0]

st.metric(
    label="Predicted Heater Duty",
    value=f"{predicted_duty:.2f} kW",
)

st.caption(
    "Prediction generated by the best-performing model "
    "(selected by R² during training in ai_model.py)."
)
